Soarya website/accounts/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 10 16:22:10 2017

@author: yizhouz
"""

from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^register/$',views.register,name = 'register'),
    url(r'^signup/$',views.signup,name = 'signup'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

Soarya website/julso/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from soarya import views
#from registration.backends.simple.views import RegistrationView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.Index,name='home'),
    url(r'^soarya/',include('soarya.urls')),
    url(r'^accounts/',include('accounts.urls')),
    #url(r'^accounts/', include('registration.backends.simple.urls')),
    #url(r'^accounts/register/$', MyRegistrationView.as_view(),
    #    name='registration_register'),
    
]

Soarya website/soarya/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 10 16:22:10 2017

@author: yizhouz
"""

from django.conf.urls import url
from . import views

app_name = 'soarya'
urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^about/$',views.About, name = 'about'),
    url(r'^contact/$',views.Contact,name = 'contact'),
    url(r'^coming/$',views.Coming,name = 'coming'),
    url(r'^thanks/$',views.Thanks,name = 'thanks'),
    url(r'^addsoarya/$',views.Addsoarya,name='addsoarya'),
    url(r'^(?P<subject_slug>[\w\-]+)/$',views.Subject,name = 'subject'),
    url(r'^(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/$',
        views.Lesson,name = 'lesson'),

    url(r'^(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/(?P<label>(books|tutorials|blogs|courses)+)/$',views.More,name='more'),
    url(r'^(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/(?P<source_id>[\w]+)/comments$',views.CommentOn, name='comments'),
]

Soarya website/soarya/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from accounts.models import UserProfile
import datetime

from django.db import models
from django.template.defaultfilters import slugify

from accounts.models import User, UserProfile

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 100)
    rank = models.IntegerField(default = 0)
    slug = models.SlugField(blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
    
class Course(models.Model):    
    name = models.CharField(max_length = 100)
    category = models.ForeignKey(Category)
    rank = models.IntegerField(default = 0)
    column = models.IntegerField(default=0) #position for which column of listing
    
    slug = models.SlugField(blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Course, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'courses'
    def __str__(self):
        return self.name
    
class Source(models.Model):
    name = models.CharField(max_length = 200) #简称 #must have name
    #id is set automatically by django
    description = models.CharField(max_length = 2000, blank = True)
    author = models.CharField(max_length= 100, blank = True)
    link = models.URLField(max_length = 200,default = "") #must have link
    label = models.CharField(max_length = 50,blank = True)
    category = models.ForeignKey(Category) #must have
    course = models.ForeignKey(Course)
    difficulty = models.IntegerField(default = 3)
    difficulty_num = models.IntegerField(default = 1)
    score = models.IntegerField(default = 3)
    score_num = models.IntegerField(default = 1)
    pub_date = models.DateTimeField(default=timezone.now) # must have, generate automatically
    #valid_date = models.DateTimeField(blank = True)
    comment_num = models.IntegerField(default = 0)
    comment_on = models.BooleanField(default = True)
    clicks = models.IntegerField(default = 0)
    valid = models.BooleanField(default = True) #whether is valid
    owner = models.ForeignKey(User,null=True) #must have an owner
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Source, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'sources'
        
    def __str__(self):
        return self.name
    
    
class Comment(models.Model):
    content = models.CharField(max_length=2048,default="")  # comment
    owner = models.ForeignKey(User) #who posted
    pub_date = models.DateTimeField(default=timezone.now) #date
    like = models.IntegerField(default = 0) #pike
    target = models.ForeignKey(Source)#target

    score = models.IntegerField(default=3)
    difficulty = models.IntegerField(default=2)


class ContactMessage(models.Model):
    message = models.CharField(max_length=1000, default="")
    email = models.EmailField(max_length = 254, blank=True)
    name = models.CharField(max_length=128, blank=True)

Soarya website/soarya/forms.py
from django import forms


class ContactForm(forms.Form):
    message = forms.CharField(max_length=1000)
    email = forms.EmailField(max_length = 254)
    name = forms.CharField(max_length=128,required=False)

class CommentForm(forms.Form):
    content = forms.CharField(max_length=2048)  # comment
    score = forms.IntegerField()
    difficulty = forms.IntegerField()

Soarya website/soarya/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required

#About time
from django.utils import timezone
import datetime

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from soarya.models import Category,Course,Source,ContactMessage,Comment


from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django import forms
from soarya.forms import ContactForm,CommentForm
# Create your views here.

#----indexilize views
def Index(request):
    category_list = Category.objects.order_by('-rank')[:5]

    context_dict = {'categories': category_list}
    return render(request,'soarya/index.html',context_dict)


def About(request):
    return render(request,'soarya/about.html',{})

def Contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            newMessage = ContactMessage.objects.create(message = form.cleaned_data['message'],
                            email = form.cleaned_data['email'],name = form.cleaned_data['name'])
            newMessage.save()
            return HttpResponseRedirect(reverse('soarya:thanks'))
    else:
        form = ContactForm()

    return render(request,'soarya/contact.html',{'form':form})
    #return render(request,'soarya/contact.html',{})

def Coming(request):
    return render(request,'soarya/coming.html',{})

def Thanks(request):
    return render(request,'soarya/thanks.html',{})


#----Subject
def Subject(request,subject_slug):
    category = Category.objects.get(slug = subject_slug)
    #print(category.name)
    courses = Course.objects.filter(category__name__contains=category.name)
    
    context_dict = {'category': category,'courses':courses}
    return render(request,'soarya/list.html',context_dict)

def Lesson(request,subject_slug,course_slug):
    course = Course.objects.get(slug = course_slug)
    sources = Source.objects.filter(course__name__contains=course.name)
    tutorials = sources.filter(label='tutorial')[:5]
    books =sources.filter(label='book')[:6]
    blogs = sources.filter(label='blog')[:5]
    courses = sources.filter(label='course')[:5]


    #print(subject_slug,course_slug,'books')
    context_dict = {'subject_slug':subject_slug,'course_slug':course.slug,
                    'course':course,
                    'courses':courses,'tutorials':tutorials,'books':books,
                    'blogs':blogs}
    return render(request,'soarya/content.html',context_dict)

def More(request,subject_slug,course_slug,label):
    sources_list = Source.objects.filter(course__slug__contains=course_slug,label=label[:-1]) #books -> book
    paginator = Paginator(sources_list, 8)
    page = request.GET.get('page',1)
    #print(page)

    try:
        sources = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        sources = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        sources = paginator.page(paginator.num_pages)

    #print(sources_list)
    return render(request, 'soarya/moretable.html', {'sources':sources,'course_slug':course_slug,'label':label})



def CommentOn(request,subject_slug,course_slug,source_id):
    source = Source.objects.get(id = source_id)
    comments_list = Comment.objects.filter(target__id = source_id).order_by('-like') # books -> book
    paginator = Paginator(comments_list, 10)
    page = request.GET.get('page', 1)

    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        comments = paginator.page(paginator.num_pages)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            if request.user.is_authenticated():
                newComment= Comment.objects.create(content = form.cleaned_data['content'],
                                score = form.cleaned_data['score'],difficulty = form.cleaned_data['difficulty'],
                                target = source, owner=request.user)
                newComment.save()
                return HttpResponseRedirect(reverse('soarya:thanks'))
    else:
        form = ContactForm()


    return render(request, 'soarya/comment.html', {'comments':comments,'source':source})


def Addsoarya(request):

    back_to = request.POST.get('next', '/')

    label_dic = [('tutorial','Tutorial'),('book','Book'),('blog','Blog'),('course','Course')]

    categories = Category.objects.all()
    categories_names = tuple([(str(i),categories[i].name) for i in range(len(categories))])
    #print(categories_names)
    courses = Course.objects.all()
    courses_names = [(str(i), courses[i].name) for i in range(len(courses))]

    class AddForm(forms.Form):
        category = forms.ChoiceField(choices = categories_names)
        course = forms.ChoiceField(choices=courses_names)
        label = forms.ChoiceField(choices = label_dic)
        name = forms.CharField(max_length=100)
        link = forms.URLField()
        author = forms.CharField(max_length = 100)
        description = forms.CharField(
            max_length=1200,
            widget=forms.Textarea(),
            help_text='optional',
            required=False
        )
        score = forms.IntegerField(min_value=0, max_value=5)
        difficulty = forms.IntegerField(min_value=0, max_value=5)

    if request.method == 'POST':
        add_form = AddForm(request.POST)
        if add_form.is_valid():
            cate = categories_names[int(add_form.cleaned_data['category'])][1]
            cour = courses_names[int(add_form.cleaned_data['course'])][1]
            name = add_form.cleaned_data['name']
            link = add_form.cleaned_data['link']
            auth = add_form.cleaned_data['author']
            scor = add_form.cleaned_data['score']
            diff = add_form.cleaned_data['difficulty']

            category = Category.objects.get(name=cate)
            course = Course.objects.get(name=cour)
            source = Source.objects.get_or_create(name=name, category=category, course=course)[0]
            source.author = auth
            source.link = link
            source.label = add_form.cleaned_data['label']
            source.save()

            #return HttpResponseRedirect(back_to)
            return HttpResponseRedirect(reverse('soarya:index'))


    else:
         add_form = AddForm()

    return render(request, 'soarya/add.html', {'form':add_form})

Soarya website/templates/soarya/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title></title>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
            <link rel="stylesheet" href="{% static 'assets/css/404.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/add.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/banner.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/comment.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/contact.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/content.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/Footer-Basic.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/listtable.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/Login-Form-Dark.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/nav.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/register.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/search.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/tab.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/team.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/wrapper.css' %}">
    </head>
    <body>
        <nav id="header" class="navbar-fixed-top" style="margin-bottom:0px">
            <div class="container-fluid" id="navfluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">
                       <span class="sr-only">Toggle navigation</span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                    </button>
                    <h1><a href="index.html">Soarya-Beta-0.2</a></h1>
                </div>
                <nav class="collapse navbar-collapse" id="navigationbar">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'soarya:index' %}">Home</a></li>
                        <li><a href="{% url 'soarya:coming' %}">Notes</a></li>
                        <li><a href="{% url 'soarya:coming' %}">Tools</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="">Hello {{user.username }}</a></li>
                        <li><a href="{% url 'accounts:logout' %}" >Logout</a></li>
                        <li><a href="{% url 'soarya:addsoarya' %}?next={{ request.path }}" class="button special">+ Soarya</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:signup' %} ">Register</a></li>
                        <li><a href="{% url 'accounts:login' %}?next={{ request.path }}" class="button special">Sign In/Up</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </nav>
        {% block body_block %}
        {% endblock %}
        <div class="footer-basic">
            <footer>
                <div class="social"><a href="https://mail.google.com"><i class="fa fa-google"></i></a>
                    <!--<a href="">
                    <i class="fa fa-snapchat-ghost"></i></a-->
                    <a href="https://twitter.com/?lang=en"><i class="fa fa-twitter"></i></a>
                    <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></div>
                <ul class="list-inline">
                    <li><a href="{% url 'soarya:index' %}">Home</a></li>
                    <li><a href="{% url 'soarya:contact' %}">Contact</a></li>
                    <li><a href="{% url 'soarya:about' %}">About</a></li>
                    <!--<li><a href="#">Terms</a></li>
                    <li><a href="#">Privacy Policy</a></li>-->
                </ul>
                <p class="copyright">Sourya © 2017</p>
            </footer>
        </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>

Soarya website/templates/soarya/coming.html
{% extends "soarya/base.html" %}
{% block body_block %}
<div class="error">
    <div class="error-code m-b-10 m-t-20"><i class="fa fa-plane"></i>  Coming soon...</div>
        <h3 class="font-bold">This page will come in the near future</h3>

    <div class="error-desc">
            Sorry, but the page you are looking for was either not found or does not exist. <br/>
            Try refreshing the page or click the button below to go back to the Homepage.
        <div>
        <a class=" login-detail-panel-button btn" href="{% url 'soarya:index' %}">
        <i class="fa fa-arrow-left"></i>
        Go back to Homepage                        
        </a>
        </div>
    </div>
</div>
{% endblock %}

Soarya website/templates/soarya/index.html
{% extends "soarya/base.html" %}
{% block body_block %}
{% load staticfiles%}

    <!-- Banner -->
<section id="banner">
    <div class="container">
        <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <form action="#" method="#" role="search">
                <div class="input-group">
                    <input class="form-control" placeholder="Search . . ." name="srch-term" id="ed-srch-term" type="text">
                    <div class="input-group-btn">
                    <button type="submit" id="searchbtn">
                    search</button>
                    </div>
                </div>
            </form>
        </div>
        </div>
    </div>
    <p>Better Study, Better Career, Better Life</p>
    <!--<ul class="actions">
        <li>
            <a href="#" class="button middle">Lorem ipsum dolor</a>
        </li>
    </ul>
    -->
</section>
    <!-- One -->
			<section id="one" class="wrapper style1 special">
				<div class="container">
					<header class="major">
						<h2>Start your journey</h2>
						<p>.....................</p>
					</header>
					<div class="row">
						<div class="4u 12u$(medium) col-md-4">
							<section class="box">
								<i class="icon big rounded color0 fa-table"></i>
								<h3>Statistics</h3>
                                    <div><i class = 'fa fa-th'></i><a href="{% url 'soarya:lesson' subject_slug='statistics' course_slug='probability' %}">&nbsp Probability</a></div>
                                    <div><i class = 'fa fa-database'></i><a href="{% url 'soarya:lesson' subject_slug='statistics' course_slug='statistics' %}">&nbsp Statistics</a></div>
                                    <div><i class = 'fa fa-random'></i><a href="{% url 'soarya:lesson' subject_slug='statistics' course_slug='probability' %}">&nbsp Random Processes</a></div>
                                    <div><a href="{%url 'soarya:subject' subject_slug='statistics'  %}">
										...more</a></div>
                            </section>
						</div>
						<div class="4u 12u$(medium) col-md-4">
							<section class="box">
								<i class="icon big rounded color9 fa-desktop"></i>
								<h3>Computer Science</h3>
								<div><i class = 'fa fa-truck'></i><a href='url'>&nbsp Web Development</a></div>
								<div><i class = 'fa fa-graduation-cap'></i><a href='url'>&nbsp Machine Learning</a></div>
								<div><i class = 'fa fa-question'></i><a href='url'>&nbsp Coming soon</a></div>
								<div><a href="{%url 'soarya:subject' subject_slug='computer-science'  %}">
										...more</a></div>
 							</section>
						</div>
						<div class="4u$ 12u$(medium) col-md-4">
							<section class="box">
								<i class="icon big rounded color6 fa-heart-o	"></i>
								<h3>Psycology</h3>
								<p>
									Thanks for you attention, this part well come soon.
								</p>
							</section>
						</div>
					</div>
					<div class="row">
						<div class="4u$ 12u$(medium) col-md-4">
							<section class="box">
								<i class="icon big rounded color6 fa-rocket"></i>
								<h3>Philosophy</h3>
								<p>
									Thanks for you attention, this part well come soon.
								</p>
							</section>
						</div>
						<div class="4u$ 12u$(medium) col-md-4">
							<section class="box">
								<i class="icon big rounded color6 fa-rocket"></i>
								<h3>Art</h3>
								<p>
									Thanks for you attention, this part well come soon.
								</p>
							</section>
						</div>
						<div class="4u$ 12u$(medium) col-md-4">
							<section class="box">
								<i class="icon big rounded color6 fa-rocket"></i>
								<h3>Coming soon...</h3>
								<p>
									Thanks for you attention, this part well come soon.
								</p>
							</section>
						</div>
					</div>
				</div>
			</section>
    <!-- Two -->
			<!-- Two -->
			<section id="two" class="wrapper style2 special">
    <div class="container">
        <header class="major">
            <h2>Our Team</h2>
            <p class="text-success">We started Soarya when attending Berkeley and aimed to build the education resources search engine
                and knowledge map to provide the most efficient way of learning to make everyone more productive, more organized, more goal-oriented in their education journey.<p>
        </header>
        <section class="profiles">
            <div class="row">
                <div class="col-md-3 col-sm-3 team-wrap">
                  <div class="team-member text-center">
                    <div class="team-img">
                      <img src="{% static 'assets/img/team/yizhou.jpg' %}" alt="">
                      <div class="overlay">
                        <div class="team-details text-center">
                          <p>
                            Yizhou loves coding, art and philosophy. He believes that education is the social welfare for everyone.
                          </p>
                          <div class="socials mt-20">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-envelope"></i></a>
                          </div>
                        </div>
                      </div>
                    </div>

                    <h6 class="team-title">Database/Website Developer</h6>
                    <span> Yizhou Zhao</span>
                  </div>
                </div>

                <!--kara-->
                <div class="col-md-3 col-sm-3 team-wrap">
                  <div class="team-member text-center">
                    <div class="team-img">
                      <img src="{% static 'assets/img/team/kara.jpg' %}" alt="">
                      <div class="overlay">
                        <div class="team-details text-center">
                          <p>
                           Kara is always passionate about education. She wants to provide the life-long learning opportunities and a permanent record of all your study activities.
                          </p>
                          <div class="socials mt-20">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-envelope"></i></a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <h6 class="team-title">Designer/Founder</h6>
                    <span>Kara Yang</span>
                  </div>
                </div>

                <!--karan-->
                <div class="col-md-3 col-sm-3 team-wrap">
                  <div class="team-member text-center">
                    <div class="team-img">
                      <img src="{% static 'assets/img/team/kailai.jpg' %}" alt="">
                      <div class="overlay">
                        <div class="team-details text-center">
                          <p>
                            Kailai is a workaholic. He never feels tired about studying and researching.
                          </p>
                          <div class="socials mt-20">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-envelope"></i></a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <h6 class="team-title">Consultant</h6>
                    <span>Kailai Xu</span>
                  </div>
                </div>
                 <div class="col-md-3 col-sm-3 team-wrap">
                  <div class="team-member text-center">
                    <div class="team-img">
                      <img src="http://placehold.it/576x862" alt="">
                      <div class="overlay">
                        <div class="team-details text-center">
                          <p>
                            Karen is a night owl. She loves to start programming in the midnight.
                          </p>
                          <div class="socials mt-20">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-envelope"></i></a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <h6 class="team-title">Consultant</h6>
                    <span>Karen Lu</span>
                  </div>
                </div>
            </div>
            <footer>
            <p></p>
            <ul class="actions">
                <li>
                    <a href="#" class="button big">Join us</a>
                </li>
            </ul>
            </footer>
        </section>
    </div>
</section>

{% endblock %}

Soarya website/templates/soarya/lesson.html
<html>
<head>
<title>Course</title>
</head>

<body>
    <h1>{{ course.name }}</h1>
    {% for source in course.source_set.all %}
    <li>
        <a href = "{{source.link}}">{{ source.name }}</a>-Diff:{{source.difficulty}}-Score:{{source.score}}
    </li>
    {% endfor %}
</body>
</html>

Soarya website/templates/soarya/list.html
{% extends "soarya/base.html" %}
{% block body_block %}
{% load staticfiles%}
    <div id="index_header">
        <h2 class="index_title"><strong>~{{category.name}}</strong></h2>
	</div>
    <div class="row">
        <div class="col-sm-12">
            <div>
                <div class="container">
					<div class="row col-list">
						<div class="col-md-4 t1">
							<div class="col-head text-center">
								<span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
								<h2>Theory</h2>
							</div>
							<ul class="list-unstyled">
								{% for course in courses %}
								{% if course.column == 0 %}
							 <li>
								<p class="option"><span class="fa fa-arrow-right" aria-hidden="true"></span>
									<a href="{% url 'soarya:lesson' subject_slug=category.slug course_slug=course.slug %}">{{course.name}}</a></p>
							 </li>
								{% endif %}
								{% endfor %}
							</ul>
						</div>
						<div class="col-md-4 t2">
							<div class="col-head text-center">
								<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
								<h2>Practice</h2>
							</div>
							<ul class="list-unstyled">
								{% for course in courses %}
								{% if course.column == 1 %}
							 <li>
								<p class="option"><span class="fa fa-arrow-right" aria-hidden="true"></span>
									<a href="{% url 'soarya:lesson' subject_slug=category.slug course_slug=course.slug %}">{{course.name}}</a></p>
							 </li>
								{% endif %}
								{% endfor %}
							</ul>
						</div>
						<div class="col-md-4 t3">
							<div class="col-head text-center">
								<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
								<h2>Others</h2>
							</div>
							<ul class="list-unstyled">
							 <li>
								<p class="option"><span class="fa fa-arrow-right" aria-hidden="true"></span>
									<a>Coming soon</a></p>
							 </li>

							</ul>
						</div>
					</div>
  					<hr />
				</div>
			</div>
		</div>
	</div>
{% endblock %}

Soarya website/templates/soarya/subject.html
{% load staticfiles %}
<html>
<head>
<title>Sourya Index</title>
</head>
<body>
    <h1>{{category.name}}</h1>
    {% for course in category.course_set.all %}
    <li>
        <!--a href = "/soarya/{{ category.slug }}/{{ course.slug }}/">----{{ course.name }}</a-->
        <a href = "{% url 'soarya:lesson' subject_slug=category.slug course_slug=course.slug %}">----{{ course.name }}</a>
    </li>
    {% endfor %}
</body>
</html>

Soarya website/templates/soarya/thanks.html
{% extends "soarya/base.html" %}
{% block body_block %}
{% load staticfiles%}

<div style="background:url(/static/assets/img/thanks.png); height:130px; margin-top:80px">
</div>
<div class="error">
    <div class="error-desc">
    <h2>Thanks for your attention!</h2>
    <div>
        <a class=" login-detail-panel-button btn" href="{% url 'soarya:index'%}">
        <i class="fa fa-arrow-left"></i>
        Go back to Homepage                        
        </a>
        </div>
    </div>
</div>
{% endblock %}