Soarya website/accounts/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 10 16:22:10 2017

@author: yizhouz
"""

from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^register/$',views.register,name = 'register'),
    url(r'^signup/$',views.signup,name = 'signup'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

Soarya website/julso/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from soarya import views
#from registration.backends.simple.views import RegistrationView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.Index,name='home'),
    url(r'^soarya/',include('soarya.urls')),
    url(r'^accounts/',include('accounts.urls')),
    #url(r'^accounts/', include('registration.backends.simple.urls')),
    #url(r'^accounts/register/$', MyRegistrationView.as_view(),
    #    name='registration_register'),
    
]

Soarya website/soarya/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 10 16:22:10 2017

@author: yizhouz
"""

from django.conf.urls import url
from . import views

app_name = 'soarya'
urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^about/$',views.About, name = 'about'),
    url(r'^contact/$',views.Contact,name = 'contact'),
    url(r'^coming/$',views.Coming,name = 'coming'),
    url(r'^thanks/$',views.Thanks,name = 'thanks'),
    url(r'^addsoarya/$',views.Addsoarya,name='addsoarya'),
    url(r'^(?P<subject_slug>[\w\-]+)/$',views.Subject,name = 'subject'),
    url(r'^(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/$',
        views.Lesson,name = 'lesson'),

    url(r'^(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/(?P<label>(books|tutorials|blogs|courses)+)/$',views.More,name='more'),
    url(r'^(?P<subject_slug>[\w\-]+)/(?P<course_slug>[\w\-]+)/(?P<source_id>[\w]+)/comments$',views.CommentOn, name='comments'),
]

Soarya website/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.forms import UserCreationForm
from django import forms
# Create your models here.
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    
    website = models.URLField(blank = True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __str__(self):
        return self.user.username

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

Soarya website/accounts/forms.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 13 12:09:58 2017

@author: yizhouz
"""
from accounts.models import UserProfile, User

from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website','picture')

Soarya website/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from django import forms
from accounts.models import UserProfile,SignUpForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from accounts.forms import UserForm,UserProfileForm
# Create your views here.
def Index(request):
    return HttpResponse("Account")
    
def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()
            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()
            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user
            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            #put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                # Now we save the UserProfile model instance.
            profile.save()
                # Update our variable to indicate that the template
                # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    # Render the template depending on the context.
    return render(request,
    'accounts/register.html',
    {'user_form': user_form,
    'profile_form': profile_form,
    'registered': registered})
    
def user_login(request):
    back_to = request.POST.get('next', '/')
    #redirect_to = request.GET['next']
# If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
# Gather the username and password provided by the user.
# This information is obtained from the login form.
# We use request.POST.get('<variable>') as opposed
# to request.POST['<variable>'], because the
# request.POST.get('<variable>') returns None if the
# value does not exist, while request.POST['<variable>']
# will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')
# Use Django's machinery to attempt to see if the username/password
# combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
# If we have a User object, the details are correct.
# If None (Python's way of representing the absence of a value), no user
# with matching credentials was found.
        if user:
# Is the account active? It could have been disabled.
            if user.is_active:
            # If the account is valid and active, we can log the user in.
            # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect(back_to)
                return HttpResponseRedirect(reverse('soarya:index'))
                #return HttpResponse("Your Rango account is abled.")
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Soarya account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'accounts/signin.html', {})
    
    
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return render(request,'accounts/logout.html',{})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request,'soarya/index.html',None)
    else:
        form = SignUpForm()

    return render(request, 'accounts/signup.html', {'form': form})

Soarya website/templates/accounts/login.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Julso</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}">
    </head>
    {% block body_block %}
    
    <body>
        <div id="header">
            <div class="wrapper clearfix">
                <nav class="navbar navbar-findcond navbar-fixed-top">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">Soarya</a>
                        </div>
                        <div class="collapse navbar-collapse" id="navbar">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="#"><i class="fa fa-book fa-lg fa-fw"></i>Tutorials</a></li>
                                <li><a href="#"><i class="fa fa-cog fa-lg fa-fw"></i>Tools</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Profile</a></li>
                                        <li class="divider"></li>
                                        <li><a href="#">Logout</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <div id="fullscreen_bg" class="fullscreen_bg">
            <div class="form-signin">
                <div>
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4">
                            <div class="panel panel-default">
                                <div class="form-signin">
                                    <form id = "login_form" method = "post" action="{% url 'accounts:login' %}">
                                        {% csrf_token %}
                                        <h3 class="text-center">Login</h3>
                                        <div class="form-group">
                                            <div class="input-group"><span class="input-group-addon"><span class="glyphicon glyphicon-envelope"> </span></span>
                                                <input class="form-control" type="text" placeholder="Username" name="username">
                                                    </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="input-group"><span class="input-group-addon"><span class="glyphicon glyphicon-lock"> </span></span>
                                                <input class="form-control"placeholder="Password" type="password" name="password">
                                                </div>
                                            
                                            <button class="btn btn-default btn-lg btn-block" type="submit">Login
                                             </button>
                                        </div>
                                        
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-basic">
            <footer>
                <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
                <ul class="list-inline">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Terms</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
                <p class="copyright">Sourya © 2017</p>
            </footer>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
    
    {% endblock %}
    
</html>

Soarya website/templates/accounts/login1.html
{% extends "soarya/base.html" %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}
<h1>Login to Soarya</h1>
<!--<form id="login_form" method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>-->
<form id = "login_form" method = "post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <h3 class="text-center">Login</h3>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"> </span></span>
            <input type="text" placeholder="Username" name="username" value="">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group"><span class="input-group-addon"><span class="glyphicon glyphicon-lock"> </span></span>
            <input placeholder="Password" type="password" name="password" value="">
        </div>
    </div>
    <input type="submit" value = "submit">
</form>
{% endblock %}

Soarya website/templates/accounts/loginqq.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Julso</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/styles.min.css">
</head>

<body>
    <div id="header">
        <div class="wrapper clearfix">
            <nav class="navbar navbar-findcond navbar-fixed-top">
    <div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Soarya</a>
		</div>
		<div class="collapse navbar-collapse" id="navbar">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#"><i class="fa fa-book fa-lg fa-fw"></i>Tutorials</a></li>
				<li><a href="#"><i class="fa fa-cog fa-lg fa-fw"></i>Tools</a></li>
                <li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Profile</a></li>
						<li class="divider"></li>
						<li><a href="#">Logout</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>
        </div>
    </div>
    <div id="fullscreen_bg" class="fullscreen_bg">
        <div class="form-signin">
            <div>
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <div class="panel panel-default">
                            <div class="form-signin">
                                <form id = "login_form" method = "post" action="{% url 'accounts:login' %}">
                                    {% csrf_token %}
                                    <h3 class="text-center">Login</h3>
                                    <div class="form-group">
                                        <div class="input-group"><span class="input-group-addon"><span class="glyphicon glyphicon-envelope"> </span></span>
                                            <input class="form-control" type="text" placeholder="Username" name="username">
                                                </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group"><span class="input-group-addon"><span class="glyphicon glyphicon-lock"> </span></span>
                                            <input class="form-control" type="text" placeholder="Password" type="password" name="password">
                                                </div>
                                    </div>
                                    <button class="btn btn-default btn-lg btn-block" type="button"><input type="submit" value="submit">login</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <li><a href="#">Home</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Terms</a></li>
                <li><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Sourya © 2017</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>

Soarya website/templates/accounts/logout-1.html
{% extends "soarya/base.html" %}
{% block body_block %}
<h1>Logged Out</h1>
<p>You are now logged out.</p>
{% endblock %}

Soarya website/templates/accounts/logout.html
{% extends "soarya/base.html" %}
{% block body_block %}
{% load staticfiles%}

    <div class="error">
    <div class="error-desc">
    <h2>Successfully logged out...</h2>
    <div>
        <a class=" login-detail-panel-button btn" href="{% url 'soarya:index' %}">
        <i class="fa fa-arrow-left"></i>
        Go back to Homepage                        
        </a>
        </div>
    </div>
{% endblock %}

Soarya website/templates/accounts/register.html
{% extends "soarya/base.html" %}
{% load staticfiles %}
{% block title_block %}
Register
{% endblock %}

{% block body_block %}
<h1>Register Page</h1>
    {% if registered %}
    Soarya: <strong>thank you for registering!</strong>
    <a href = "{url 'soarya:index'}">Back to homepage</a>
    {% else %}
    <strong>register here!</strong><br />
 <form id="user_form" method="post" action="{% url 'accounts:register' %}"
     enctype="multipart/form-data">
     {% csrf_token %}
    
     <!-- Display each form -->
     {{ user_form.as_p }}
     {{ profile_form.as_p }}
    
     <!-- Provide a button to click to submit the form. -->
     <input type="submit" name="submit" value="Register" />
     </form>
 {% endif %}

{% endblock %}

Soarya website/templates/accounts/registration_complete.html
{% extends "soarya/base.html" %}
{% block body_block %}
<h1>Registration Complete</h1>
<p>You are now registered</p>
{% endblock %}

Soarya website/templates/accounts/signin.html
{% extends "soarya/base.html" %}
{% block body_block %}
{% load staticfiles%}
    <div class="login-dark">
        <form method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <input type="hidden"  name="next" value="{{ request.GET.next }}">
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><i class="fa fa-lock"></i></div>
            <div class="form-group">
                <!--input class="form-control" type="email" name="email" placeholder="Email">-->
                 <input class="form-control" type="text" placeholder="Username" name="username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Log In</button>
            </div><a href="{% url 'soarya:coming'%}" class="forgot">Forgot your email or password?</a>
            <a href="{% url 'accounts:signup'%}" class="forgot">
            <span style="text-decoration: underline;">Register</span> </a>
        </form>
    </div>
{% endblock %}

Soarya website/templates/accounts/signup.html
{% extends "soarya/base.html" %}
{% block body_block %}
{% load staticfiles%}
    		<div class="login-dark">
			<div class="row main">
				<div class="main-login main-center">
					<form class="form-horizontal" method="post" action="#">
                        {% csrf_token %}
                        {% for field in form %}
						<div class="form-group">
							<label>{{field.label_tag}}</label>
							<div class="cols-sm-10">
								<div class="input-group">
									{% if forloop.counter == 1 %}
									<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
									{% elif forloop.counter == 2 %}
									<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
									{% else %}
									<span class="input-group-addon"><i class="fa fa-lock fa" aria-hidden="true"></i></span>
									{% endif %}
									<!--<input type="text" class="form-control" name="email" id="email"  placeholder="Enter your Email"/>-->
                                    {{ field }}
								</div>
							</div>
						</div>
                        {% for error in field.errors %}
                              <p style="color: red">{{ error }}</p>
                        {% endfor %}
                        {% endfor %}

						<div class="form-group ">
							<button type="submit" class="btn btn-lg btn-block login-button button big">Register</button>
						</div>
						<div class="login-register">
				            <a href="{% url 'accounts:login'%}">Login</a>
				         </div>
					</form>
				</div>
			</div>
		</div>
{% endblock %}